# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3'

services:
  app:
    container_name: ${APP_NAME}-golang
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: ${APP_NAME}-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
